
// This file was auto-generated by ML.NET Model Builder. 

using RestaurantViolations_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
RestaurantViolations.ModelInput sampleData = new RestaurantViolations.ModelInput()
{
    InspectionType = @"Routine - Unscheduled",
    ViolationDescription = @"Inadequately cleaned or sanitized food contact surfaces",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual RiskCategory with predicted RiskCategory from sample data...\n\n");


Console.WriteLine($"InspectionType: {@"Routine - Unscheduled"}");
Console.WriteLine($"ViolationDescription: {@"Inadequately cleaned or sanitized food contact surfaces"}");
Console.WriteLine($"RiskCategory: {@"Moderate Risk"}");


var sortedScoresWithLabel = RestaurantViolations.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

